Feature/Venture
della-padula/Notissu pull request #157
Opened 2022-08-01 18:57 UTC by ju-djangun

벤처중소기업학과 파싱하는 코드 약간 추가했습니다.

Swift가 처음이라 테스트도 못하고 빌드도 못해서 일단 develop으로 PR합니다. 양해 부탁드리겠습니다.

NoticeURL, NoticeBusiness, NoticeParser 만 수정했는데 프로젝트 구조를 아직 잘 파악하지 못해 추가 작업이 필요한 부분을 코멘트로 알려주시면 감사하겠습니다.

2022-08-02 12:51 UTC, della-padula requested changes
두 가지만 수정해주시면 머지 해드리겠습니다.
소중한 PR 감사합니다.

2022-08-02 12:51 UTC, della-padula commented on SoongsilNotice/NoticeParser/NoticeParser.swift
> +            let url = link?["href"] ?? ""
link?에서 ? 제거해주시면 좋겠습니다.

2022-08-02 12:51 UTC, della-padula commented on SoongsilNotice/NoticeParser/NoticeParser.swift
> +        let contentHTML = html.css("div[class^='td-box']").first?.innerHTML ?? ""
td_box로 변경해주세요. 현재 코드로는 파싱이 되지 않고 있는데 사이트를 보니 td_box로 되어 있네요.

2022-08-02 13:03 UTC, ju-djangun commented
수정 완료했습니다. 실수 지적해주셔서 감사합니다.

2022-08-04 13:08 UTC, della-padula approved these changes

2022-08-04 13:08 UTC, merged